"""Add model_name to Message

Revision ID: 720220f28022
Revises: 
Create Date: 2025-08-02 18:24:11.613063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720220f28022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###
